apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-06-20T14:06:49Z"
  generation: 1
  labels:
    app: backend
  name: backend
  namespace: default
  resourceVersion: "85387"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/backend
  uid: a23e1268-5746-40c1-ae8e-41e87198c80d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: kaigitti/vuejs-backend:1
        imagePullPolicy: IfNotPresent
        name: vuejs-backend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-06-20T14:06:51Z"
    lastUpdateTime: "2020-06-20T14:06:51Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-06-20T14:06:49Z"
    lastUpdateTime: "2020-06-20T14:06:51Z"
    message: ReplicaSet "backend-754b776c8f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
