apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-21T08:04:19Z"
  labels:
    app: adder
  name: adder
  namespace: b6027315
  resourceVersion: "4576"
  selfLink: /api/v1/namespaces/default/services/adder
  uid: e71f5d68-b571-400d-a168-e4267e006f9f
spec:
  clusterIP: 10.100.32.212
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32357
    port: 9092
    protocol: TCP
    targetPort: 9090
  selector:
    app: adder
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.17.0.203
