apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-21T07:42:29Z"
  labels:
    app: front
  name: front
  namespace: b6027315
  resourceVersion: "2063"
  selfLink: /api/v1/namespaces/default/services/front
  uid: 0313c244-d43f-479f-9782-0c481919f996
spec:
  clusterIP: 10.108.239.86
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31539
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: front
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.17.0.201
