apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-21T07:58:38Z"
  labels:
    app: front
  name: front
  namespace: b6027315
  resourceVersion: "3915"
  selfLink: /api/v1/namespaces/default/services/front
  uid: a42157a0-8ca2-4bbb-a384-8264a7dba0ec
spec:
  clusterIP: 10.100.151.62
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32087
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: front
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.17.0.201
