apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-06-21T07:53:50Z"
  generation: 1
  labels:
    app: source
  name: source
  namespace: b6027315
  resourceVersion: "3373"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/source
  uid: b6c0cae1-d1a8-4bb1-aae1-27ff9e80c69f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: source
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: source
    spec:
      containers:
      - image: chanwit/source
        imagePullPolicy: Always
        name: source
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-06-21T07:53:56Z"
    lastUpdateTime: "2020-06-21T07:53:56Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-06-21T07:53:50Z"
    lastUpdateTime: "2020-06-21T07:53:56Z"
    message: ReplicaSet "source-665947f77f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
