apiVersion: v1
kind: Service
metadata:
  labels:
    app: front
  name: front
  namespace: b6027315
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: front
  sessionAffinity: None
  type: ClusterIP
